/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica2;

import java.awt.Color;
import java.awt.Image;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.InetSocketAddress;
import java.net.Socket;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.ImageIcon;

/**
 *
 * @author Christian Iván
 */
public class Compra extends javax.swing.JFrame {
  
 String nomj="";
 int cant=0;
 float precio=0;
 Calendar fi,ff;
 float promo=0;
 float total=0;
 public static int salir=0;
 int cantv[]=new int[5];
 float preciov[]=new float[5];
 public static ArrayList<Producto> cat; 
 public static Socket cl;
 public static ObjectOutputStream oos;
 public static ObjectInputStream ois;
    /**
     * Creates new form Compra
     */
    public Compra() {
        initComponents();
        lbl1.setBackground(Color.black);
        lbl2.setBackground(Color.black);
        lbl3.setBackground(Color.black);
        lbl4.setBackground(Color.black);
        lbl5.setBackground(Color.black);
        lbl6.setBackground(Color.black);
        lbl7.setBackground(Color.black);
    }
    
 public int Oferta(Calendar fi, Calendar ff)
 {
     Calendar diahoy=Calendar.getInstance();
     int C1=0;
     if((diahoy.get(Calendar.MONTH)+1)>fi.get(Calendar.MONTH)&&(diahoy.get(Calendar.MONTH)+1)<ff.get(Calendar.MONTH))
     {
         C1=1;
     }
     if((diahoy.get(Calendar.MONTH)+1)==fi.get(Calendar.MONTH)&&diahoy.get(Calendar.DATE)>=fi.get(Calendar.DATE)&&(diahoy.get(Calendar.MONTH)+1)==ff.get(Calendar.MONTH)&&diahoy.get(Calendar.DATE)<=ff.get(Calendar.DATE))
     {
         C1=1;
     }
     if((diahoy.get(Calendar.MONTH)+1)>fi.get(Calendar.MONTH)&&(diahoy.get(Calendar.MONTH)+1)==ff.get(Calendar.MONTH)&&diahoy.get(Calendar.DATE)<=ff.get(Calendar.DATE))
     {
         C1=1;
     }
     if((diahoy.get(Calendar.MONTH)+1)==fi.get(Calendar.MONTH)&&diahoy.get(Calendar.DATE)>=fi.get(Calendar.DATE)&&(diahoy.get(Calendar.MONTH)+1)<ff.get(Calendar.MONTH))
     {
         C1=1;
     }
     return C1;
 }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblImagen = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        cmbJuego = new javax.swing.JComboBox<>();
        lbl3 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        lbl4 = new javax.swing.JLabel();
        lblCantidad = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();
        lblpromo = new javax.swing.JLabel();
        lbl7 = new javax.swing.JLabel();
        spnCant = new javax.swing.JSpinner();
        btnAñadir = new javax.swing.JButton();
        btnQuitar = new javax.swing.JButton();
        btnVer = new javax.swing.JButton();
        btnComprar = new javax.swing.JButton();
        lbl5 = new javax.swing.JLabel();
        lblfi = new javax.swing.JLabel();
        lbl6 = new javax.swing.JLabel();
        lblff = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Snap ITC", 0, 18)); // NOI18N
        jLabel1.setText("Bienvenido a Steam");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        lblImagen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(lblImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 190, 150));

        lbl1.setFont(new java.awt.Font("Showcard Gothic", 0, 11)); // NOI18N
        lbl1.setText("Slecciona algun juego:");
        jPanel1.add(lbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, -1, -1));

        cmbJuego.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Helltaker", "Skullgirls", "Among us", "The witcher 3", "Undertale" }));
        cmbJuego.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbJuegoItemStateChanged(evt);
            }
        });
        jPanel1.add(cmbJuego, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, -1, -1));

        lbl3.setBackground(new java.awt.Color(255, 255, 255));
        lbl3.setFont(new java.awt.Font("Showcard Gothic", 0, 11)); // NOI18N
        lbl3.setText("Numero disponibles:");
        jPanel1.add(lbl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, -1, -1));

        lbl2.setBackground(new java.awt.Color(255, 255, 255));
        lbl2.setFont(new java.awt.Font("Showcard Gothic", 0, 11)); // NOI18N
        lbl2.setText("Precio:");
        jPanel1.add(lbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, -1, -1));

        lbl4.setFont(new java.awt.Font("Showcard Gothic", 0, 11)); // NOI18N
        lbl4.setText("OFERTA:");
        jPanel1.add(lbl4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, -1, -1));

        lblCantidad.setFont(new java.awt.Font("Showcard Gothic", 0, 11)); // NOI18N
        lblCantidad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
        jPanel1.add(lblCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, 100, 20));

        lblPrecio.setFont(new java.awt.Font("Showcard Gothic", 0, 11)); // NOI18N
        lblPrecio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
        jPanel1.add(lblPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 170, 20));

        lblpromo.setFont(new java.awt.Font("Showcard Gothic", 0, 11)); // NOI18N
        lblpromo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
        jPanel1.add(lblpromo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 180, 20));

        lbl7.setFont(new java.awt.Font("Showcard Gothic", 0, 11)); // NOI18N
        lbl7.setText("Cantidad a comprar");
        jPanel1.add(lbl7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        spnCant.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnCantStateChanged(evt);
            }
        });
        jPanel1.add(spnCant, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 50, -1));

        btnAñadir.setText("Añadir al carro");
        btnAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirActionPerformed(evt);
            }
        });
        jPanel1.add(btnAñadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, -1, -1));

        btnQuitar.setText("Quitar del carro");
        btnQuitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarActionPerformed(evt);
            }
        });
        jPanel1.add(btnQuitar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, -1, -1));

        btnVer.setText("Visualizar Carro");
        btnVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerActionPerformed(evt);
            }
        });
        jPanel1.add(btnVer, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        btnComprar.setText("Comprar");
        btnComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarActionPerformed(evt);
            }
        });
        jPanel1.add(btnComprar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 100, -1));

        lbl5.setFont(new java.awt.Font("Showcard Gothic", 0, 11)); // NOI18N
        lbl5.setText("Fecha de inicio:");
        jPanel1.add(lbl5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, -1, -1));

        lblfi.setFont(new java.awt.Font("Showcard Gothic", 0, 11)); // NOI18N
        lblfi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
        jPanel1.add(lblfi, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, 130, 20));

        lbl6.setBackground(new java.awt.Color(255, 255, 255));
        lbl6.setFont(new java.awt.Font("Showcard Gothic", 0, 11)); // NOI18N
        lbl6.setText("Fecha limite:");
        jPanel1.add(lbl6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, -1, -1));

        lblff.setFont(new java.awt.Font("Showcard Gothic", 0, 11)); // NOI18N
        lblff.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
        jPanel1.add(lblff, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, 130, 20));
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 4, 530, 380));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbJuegoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbJuegoItemStateChanged
        ImageIcon i1=new ImageIcon(cat.get(0).imagen);
        ImageIcon i2=new ImageIcon(cat.get(1).imagen);
        ImageIcon i3=new ImageIcon(cat.get(2).imagen);
        ImageIcon i4=new ImageIcon(cat.get(3).imagen);
        ImageIcon i5=new ImageIcon(cat.get(4).imagen);
        ImageIcon aux=new ImageIcon();
        switch(cmbJuego.getSelectedIndex())
        {
            case 0:
                lblCantidad.setText(""+cat.get(0).cantidadExistente);
                lblPrecio.setText(""+cat.get(0).precio);
                lblpromo.setText(""+cat.get(0).promocion);
                lblfi.setText(""+cat.get(0).inicioPromo.get(Calendar.DATE)+"-"+cat.get(0).inicioPromo.get(Calendar.MONTH)+"-"+cat.get(0).inicioPromo.get(Calendar.YEAR));
                lblff.setText(""+cat.get(0).finPromo.get(Calendar.DATE)+"-"+cat.get(0).finPromo.get(Calendar.MONTH)+"-"+cat.get(0).finPromo.get(Calendar.YEAR));
                //System.out.println(""+cat.get(0).imagen+"\n");
                aux=new ImageIcon(i1.getImage().getScaledInstance(lblImagen.getWidth(), lblImagen.getHeight(),Image.SCALE_DEFAULT));
                lblImagen.setIcon(aux);
                break;
            case 1:
                lblCantidad.setText(""+cat.get(1).cantidadExistente);
                lblPrecio.setText(""+cat.get(1).precio);
                lblpromo.setText(""+cat.get(1).promocion);
                lblfi.setText(""+cat.get(1).inicioPromo.get(Calendar.DATE)+"-"+cat.get(1).inicioPromo.get(Calendar.MONTH)+"-"+cat.get(1).inicioPromo.get(Calendar.YEAR));
                lblff.setText(""+cat.get(1).finPromo.get(Calendar.DATE)+"-"+cat.get(1).finPromo.get(Calendar.MONTH)+"-"+cat.get(1).finPromo.get(Calendar.YEAR));
                aux=new ImageIcon(i2.getImage().getScaledInstance(lblImagen.getWidth(), lblImagen.getHeight(),Image.SCALE_DEFAULT));
                lblImagen.setIcon(aux);
                break;
            case 2:
                lblCantidad.setText(""+cat.get(2).cantidadExistente);
                lblPrecio.setText(""+cat.get(2).precio);
                lblpromo.setText(""+cat.get(2).promocion);
                lblfi.setText(""+cat.get(2).inicioPromo.get(Calendar.DATE)+"-"+cat.get(2).inicioPromo.get(Calendar.MONTH)+"-"+cat.get(2).inicioPromo.get(Calendar.YEAR));
                lblff.setText(""+cat.get(2).finPromo.get(Calendar.DATE)+"-"+cat.get(2).finPromo.get(Calendar.MONTH)+"-"+cat.get(2).finPromo.get(Calendar.YEAR));
                aux=new ImageIcon(i3.getImage().getScaledInstance(lblImagen.getWidth(), lblImagen.getHeight(),Image.SCALE_DEFAULT));
                lblImagen.setIcon(aux);
                break;
            case 3:
                lblCantidad.setText(""+cat.get(3).cantidadExistente);
                lblPrecio.setText(""+cat.get(3).precio);
                lblpromo.setText(""+cat.get(3).promocion);
                lblfi.setText(""+cat.get(3).inicioPromo.get(Calendar.DATE)+"-"+cat.get(3).inicioPromo.get(Calendar.MONTH)+"-"+cat.get(3).inicioPromo.get(Calendar.YEAR));
                lblff.setText(""+cat.get(3).finPromo.get(Calendar.DATE)+"-"+cat.get(3).finPromo.get(Calendar.MONTH)+"-"+cat.get(3).finPromo.get(Calendar.YEAR));
                aux=new ImageIcon(i4.getImage().getScaledInstance(lblImagen.getWidth(), lblImagen.getHeight(),Image.SCALE_DEFAULT));
                lblImagen.setIcon(aux);
                break;
            case 4:
                lblCantidad.setText(""+cat.get(4).cantidadExistente);
                lblPrecio.setText(""+cat.get(4).precio);
                lblpromo.setText(""+cat.get(4).promocion);
                lblfi.setText(""+cat.get(4).inicioPromo.get(Calendar.DATE)+"-"+cat.get(4).inicioPromo.get(Calendar.MONTH)+"-"+cat.get(4).inicioPromo.get(Calendar.YEAR));
                lblff.setText(""+cat.get(4).finPromo.get(Calendar.DATE)+"-"+cat.get(4).finPromo.get(Calendar.MONTH)+"-"+cat.get(4).finPromo.get(Calendar.YEAR));
                aux=new ImageIcon(i5.getImage().getScaledInstance(lblImagen.getWidth(), lblImagen.getHeight(),Image.SCALE_DEFAULT));
                lblImagen.setIcon(aux);
                break;
        }
    }//GEN-LAST:event_cmbJuegoItemStateChanged

    private void btnAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirActionPerformed
        Calendar diahoy=Calendar.getInstance();
        int oferta=0;
        oferta=Oferta(cat.get(cmbJuego.getSelectedIndex()).inicioPromo,cat.get(cmbJuego.getSelectedIndex()).finPromo);
        //diahoy.set(Calendar.MONTH,diahoy.get(Calendar.MONTH+1));
        System.out.println(""+diahoy.get(Calendar.DATE)+"-"+diahoy.get(Calendar.MONTH)+"-"+diahoy.get(Calendar.YEAR));
        if(cantv[cmbJuego.getSelectedIndex()]>cat.get(cmbJuego.getSelectedIndex()).cantidadExistente)
        {
          cant=cat.get(cmbJuego.getSelectedIndex()).cantidadExistente;
         if(oferta==1)
         {
            System.out.println("Descuento aplicado");
            precio=((cat.get(cmbJuego.getSelectedIndex()).precio)-(cat.get(cmbJuego.getSelectedIndex()).promocion));
            total=total+(precio*cant);
            cantv[cmbJuego.getSelectedIndex()]=cantv[cmbJuego.getSelectedIndex()]+cant;
         }
         else
         {
           total=total+(cat.get(cmbJuego.getSelectedIndex()).precio*cant);
           cantv[cmbJuego.getSelectedIndex()]=cantv[cmbJuego.getSelectedIndex()]+cant;
         }  
        }
        else
        {
           if(oferta==1)
           {
            System.out.println("Descuento aplicado");
            precio=((cat.get(cmbJuego.getSelectedIndex()).precio)-(cat.get(cmbJuego.getSelectedIndex()).promocion));
            total=total+(precio*cant);
            cantv[cmbJuego.getSelectedIndex()]=cantv[cmbJuego.getSelectedIndex()]+cant;
           }
           else
           {
            total=total+(cat.get(cmbJuego.getSelectedIndex()).precio*cant);
            cantv[cmbJuego.getSelectedIndex()]=cantv[cmbJuego.getSelectedIndex()]+cant;
           }  
        }
        cat.get(cmbJuego.getSelectedIndex()).cantidadExistente=cat.get(cmbJuego.getSelectedIndex()).cantidadExistente-cant;
        lblCantidad.setText(""+cat.get(cmbJuego.getSelectedIndex()).cantidadExistente);
        System.out.println(""+cat.get(cmbJuego.getSelectedIndex()).nombre+" comprados "+cant);
    }//GEN-LAST:event_btnAñadirActionPerformed

    private void spnCantStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnCantStateChanged
       cant=Integer.parseInt(spnCant.getValue().toString());
    }//GEN-LAST:event_spnCantStateChanged

    private void btnQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarActionPerformed
        Calendar diahoy= Calendar.getInstance();
        int oferta=0;
        oferta=Oferta(cat.get(cmbJuego.getSelectedIndex()).inicioPromo,cat.get(cmbJuego.getSelectedIndex()).finPromo);
        for(int i=0;i<5;i++)
        {
            if(oferta==1)
            {
                preciov[i]=(cat.get(i).precio-cat.get(i).promocion);
            }
            else
            {
                preciov[i]=cat.get(i).precio;
            }
        }
        if(cant==0||cantv[cmbJuego.getSelectedIndex()]==0)
      {
          System.out.println("ERROR, este articulo no se encuentar en su carrito\n");
      }
      if(cant>cantv[cmbJuego.getSelectedIndex()])
      {
          cant=cantv[cmbJuego.getSelectedIndex()];
          total=total-(preciov[cmbJuego.getSelectedIndex()]*cantv[cmbJuego.getSelectedIndex()]);
          cantv[cmbJuego.getSelectedIndex()]=0;        
      }
      if(cant<=cantv[cmbJuego.getSelectedIndex()])
      {
           total=total-(preciov[cmbJuego.getSelectedIndex()]*cant);
          cantv[cmbJuego.getSelectedIndex()]=cantv[cmbJuego.getSelectedIndex()]-cant;     
      }
      cat.get(cmbJuego.getSelectedIndex()).cantidadExistente=cat.get(cmbJuego.getSelectedIndex()).cantidadExistente+cant;
      lblCantidad.setText(""+cat.get(cmbJuego.getSelectedIndex()).cantidadExistente);
      System.out.println(""+cat.get(cmbJuego.getSelectedIndex()).nombre+" retirados "+cant);
    }//GEN-LAST:event_btnQuitarActionPerformed

    private void btnVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerActionPerformed
        Calendar diahoy= Calendar.getInstance();
        int oferta=0;
        for(int i=0;i<5;i++)
        {
            oferta=Oferta(cat.get(i).inicioPromo,cat.get(i).finPromo);
            if(oferta==1)
            {
                preciov[i]=(cat.get(i).precio-cat.get(i).promocion);
            }
            else
            {
                preciov[i]=cat.get(i).precio;
            }
        }
        Carro v=new Carro(cantv[0],cantv[1],cantv[2],cantv[3],cantv[4],preciov[0],preciov[1],preciov[2],preciov[3],preciov[4]);
        v.setVisible(true);
    }//GEN-LAST:event_btnVerActionPerformed

    private void btnComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarActionPerformed
        System.out.println("Enviando de regreso el catalogo al servidor");
        Calendar diahoy= Calendar.getInstance();
        int oferta=0;
        for(int i=0;i<5;i++)
        {
            oferta=Oferta(cat.get(i).inicioPromo,cat.get(i).finPromo);
            if(oferta==1)
            {
                preciov[i]=(cat.get(i).precio-cat.get(i).promocion);
            }
            else
            {
                preciov[i]=cat.get(i).precio;
            }
        }
               try{
               oos.writeObject(cat);
               oos.flush();
               System.out.println("Catalogo regresado al servidor");
               ois.close();
               oos.close();
               cl.close(); 
               }catch(Exception e)
               {
                   e.printStackTrace();
               }
               this.dispose();
               Ticket t=new Ticket(cantv[0],cantv[1],cantv[2],cantv[3],cantv[4],preciov[0],preciov[1],preciov[2],preciov[3],preciov[4],total);
               t.setVisible(true);
    }//GEN-LAST:event_btnComprarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Compra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Compra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Compra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Compra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Compra().setVisible(true);
            }
        });
       
        try {
            cl=new Socket("localhost",3000);
            System.out.println("Conexion con servidor exitosa, esperando a recibir el catalogo");
            oos = new ObjectOutputStream(cl.getOutputStream());
            ois = new ObjectInputStream(cl.getInputStream());
            cat = (ArrayList<Producto>)ois.readObject();
            System.out.println("Catalogo recibido");           
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAñadir;
    private javax.swing.JButton btnComprar;
    private javax.swing.JButton btnQuitar;
    private javax.swing.JButton btnVer;
    private javax.swing.JComboBox<String> cmbJuego;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lbl5;
    private javax.swing.JLabel lbl6;
    private javax.swing.JLabel lbl7;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblff;
    private javax.swing.JLabel lblfi;
    private javax.swing.JLabel lblpromo;
    private javax.swing.JSpinner spnCant;
    // End of variables declaration//GEN-END:variables
}
